[build]
  # Directorio donde se encuentran los archivos construidos  
  publish = "dist"
  
  # Comando para construir la aplicaci칩n
  command = "npm run build"

[build.environment]
  # Versi칩n de Node.js a usar
  NODE_VERSION = "18"

# Configuraci칩n de redirects y rewrites
[[redirects]]
  # Redirigir todas las rutas no encontradas al index.html para SPA
  from = "/*"
  to = "/index.html"
  status = 200

# Headers b치sicos de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
